import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";

import { gitCheckpoint, gitRevert } from "../src/git.mjs";

function initRepository() {
  const workspace = mkdtempSync(join(tmpdir(), "gateway-git-"));
  const git = (...args) =>
    execFileSync("git", ["-C", workspace, ...args], { stdio: "pipe" });
  git("init", "--initial-branch", "main");
  git("-c", "user.name=Test", "-c", "user.email=test@example.com", "commit", "--allow-empty", "-m", "initial");
  return { workspace, git };
}

test("gitCheckpoint commits workspace changes and returns the sha", async () => {
  const { workspace, git } = initRepository();
  try {
    writeFileSync(join(workspace, "feature.txt"), "generated by an agent\n");

    const result = await gitCheckpoint(workspace, "Task 1: add feature");

    assert.equal(result.committed, true);
    assert.match(result.commitSha, /^[0-9a-f]{40}$/);
    const subject = git("log", "-1", "--format=%s").toString().trim();
    assert.equal(subject, "Task 1: add feature");
    const status = git("status", "--porcelain").toString().trim();
    assert.equal(status, "");
  } finally {
    rmSync(workspace, { recursive: true, force: true });
  }
});

test("gitCheckpoint reports a clean workspace without committing", async () => {
  const { workspace } = initRepository();
  try {
    const result = await gitCheckpoint(workspace, "Task 1: nothing changed");

    assert.equal(result.committed, false);
    assert.equal(result.commitSha, null);
  } finally {
    rmSync(workspace, { recursive: true, force: true });
  }
});

test("gitCheckpoint rejects a workspace that is not a repository root", async () => {
  const workspace = mkdtempSync(join(tmpdir(), "gateway-git-plain-"));
  try {
    await assert.rejects(
      gitCheckpoint(workspace, "Task 1: not a repo"),
      /not the root of a Git repository/,
    );
  } finally {
    rmSync(workspace, { recursive: true, force: true });
  }
});

test("gitCheckpoint validates the commit message", async () => {
  await assert.rejects(gitCheckpoint("/tmp", ""), /Commit message/);
  await assert.rejects(gitCheckpoint("/tmp", "x".repeat(501)), /Commit message/);
});

test("gitRevert undoes a checkpoint with a new revert commit", async () => {
  const { workspace, git } = initRepository();
  try {
    writeFileSync(join(workspace, "feature.txt"), "generated by an agent\n");
    const checkpoint = await gitCheckpoint(workspace, "Task 1: add feature");

    const result = await gitRevert(workspace, checkpoint.commitSha);

    assert.equal(result.reverted, true);
    assert.match(result.revertSha, /^[0-9a-f]{40}$/);
    assert.equal(existsSync(join(workspace, "feature.txt")), false);
    const subject = git("log", "-1", "--format=%s").toString().trim();
    assert.match(subject, /^Revert "Task 1: add feature"$/);
  } finally {
    rmSync(workspace, { recursive: true, force: true });
  }
});

test("gitRevert refuses a dirty working tree", async () => {
  const { workspace } = initRepository();
  try {
    writeFileSync(join(workspace, "feature.txt"), "committed\n");
    const checkpoint = await gitCheckpoint(workspace, "Task 1: add feature");
    writeFileSync(join(workspace, "uncommitted.txt"), "pending work\n");

    await assert.rejects(
      gitRevert(workspace, checkpoint.commitSha),
      /uncommitted changes/,
    );
  } finally {
    rmSync(workspace, { recursive: true, force: true });
  }
});

test("gitRevert validates the commit reference", async () => {
  await assert.rejects(gitRevert("/tmp", "HEAD~1"), /not a valid SHA/);
});
