import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";

import {
  gitCheckpoint,
  gitCreateTaskWorktree,
  gitCreateWorktree,
  gitIntegrateTaskWorktree,
  gitIntegrateWorktree,
  gitPrepareTaskResolution,
  gitRevert,
  gitTaskWorktreeReport,
} from "../src/git.mjs";

function initRepository() {
  const workspace = mkdtempSync(join(tmpdir(), "gateway-git-"));
  const git = (...args) =>
    execFileSync("git", ["-C", workspace, ...args], { stdio: "pipe" });
  git("init", "--initial-branch", "main");
  git("-c", "user.name=Test", "-c", "user.email=test@example.com", "commit", "--allow-empty", "-m", "initial");
  return { workspace, git };
}

test("gitCheckpoint commits workspace changes and returns the sha", async () => {
  const { workspace, git } = initRepository();
  try {
    writeFileSync(join(workspace, "feature.txt"), "generated by an agent\n");

    const result = await gitCheckpoint(workspace, "Task 1: add feature");

    assert.equal(result.committed, true);
    assert.match(result.commitSha, /^[0-9a-f]{40}$/);
    const subject = git("log", "-1", "--format=%s").toString().trim();
    assert.equal(subject, "Task 1: add feature");
    const status = git("status", "--porcelain").toString().trim();
    assert.equal(status, "");
  } finally {
    rmSync(workspace, { recursive: true, force: true });
  }
});

test("gitCheckpoint reports a clean workspace without committing", async () => {
  const { workspace } = initRepository();
  try {
    const result = await gitCheckpoint(workspace, "Task 1: nothing changed");

    assert.equal(result.committed, false);
    assert.equal(result.commitSha, null);
  } finally {
    rmSync(workspace, { recursive: true, force: true });
  }
});

test("gitCheckpoint rejects a workspace that is not a repository root", async () => {
  const workspace = mkdtempSync(join(tmpdir(), "gateway-git-plain-"));
  try {
    await assert.rejects(
      gitCheckpoint(workspace, "Task 1: not a repo"),
      /not the root of a Git repository/,
    );
  } finally {
    rmSync(workspace, { recursive: true, force: true });
  }
});

test("gitCheckpoint validates the commit message", async () => {
  await assert.rejects(gitCheckpoint("/tmp", ""), /Commit message/);
  await assert.rejects(gitCheckpoint("/tmp", "x".repeat(501)), /Commit message/);
});

test("gitRevert undoes a checkpoint with a new revert commit", async () => {
  const { workspace, git } = initRepository();
  try {
    writeFileSync(join(workspace, "feature.txt"), "generated by an agent\n");
    const checkpoint = await gitCheckpoint(workspace, "Task 1: add feature");

    const result = await gitRevert(workspace, checkpoint.commitSha);

    assert.equal(result.reverted, true);
    assert.match(result.revertSha, /^[0-9a-f]{40}$/);
    assert.equal(existsSync(join(workspace, "feature.txt")), false);
    const subject = git("log", "-1", "--format=%s").toString().trim();
    assert.match(subject, /^Revert "Task 1: add feature"$/);
  } finally {
    rmSync(workspace, { recursive: true, force: true });
  }
});

test("gitRevert refuses a dirty working tree", async () => {
  const { workspace } = initRepository();
  try {
    writeFileSync(join(workspace, "feature.txt"), "committed\n");
    const checkpoint = await gitCheckpoint(workspace, "Task 1: add feature");
    writeFileSync(join(workspace, "uncommitted.txt"), "pending work\n");

    await assert.rejects(
      gitRevert(workspace, checkpoint.commitSha),
      /uncommitted changes/,
    );
  } finally {
    rmSync(workspace, { recursive: true, force: true });
  }
});

test("gitRevert validates the commit reference", async () => {
  await assert.rejects(gitRevert("/tmp", "HEAD~1"), /not a valid SHA/);
});

test("worktree lifecycle isolates changes and fast-forwards only after integration", async () => {
  const { workspace, git } = initRepository();
  const worktreeRoot = mkdtempSync(join(tmpdir(), "gateway-worktrees-"));
  const runId = "4198f342-7b3d-4a21-8c11-63c7b229d880";
  try {
    const created = await gitCreateWorktree(workspace, runId, worktreeRoot);
    writeFileSync(join(created.worktree, "isolated.txt"), "mission change\n");
    const checkpoint = await gitCheckpoint(created.worktree, "Task 1: isolated change");

    assert.equal(existsSync(join(workspace, "isolated.txt")), false);
    assert.match(checkpoint.commitSha, /^[0-9a-f]{40}$/);

    const integrated = await gitIntegrateWorktree(
      workspace,
      created.worktree,
      created.branch,
      created.baselineSha,
    );

    assert.equal(integrated.integrated, true);
    assert.equal(integrated.cleaned, true);
    assert.equal(existsSync(join(workspace, "isolated.txt")), true);
    assert.equal(existsSync(created.worktree), false);
    assert.equal(git("branch", "--list", created.branch).toString().trim(), "");
  } finally {
    rmSync(worktreeRoot, { recursive: true, force: true });
    rmSync(workspace, { recursive: true, force: true });
  }
});

test("gitIntegrateWorktree copies gitignored dependency directories and .env into the registered repository", async () => {
  const { workspace } = initRepository();
  const worktreeRoot = mkdtempSync(join(tmpdir(), "gateway-worktrees-"));
  const runId = "4198f342-7b3d-4a21-8c11-63c7b229d882";
  try {
    const created = await gitCreateWorktree(workspace, runId, worktreeRoot);
    writeFileSync(join(created.worktree, ".gitignore"), "/vendor\n/.env\n/public/build\n");
    writeFileSync(join(created.worktree, "composer.json"), "{}\n");
    writeFileSync(join(created.worktree, ".env.example"), "APP_KEY=\n");
    writeFileSync(join(created.worktree, "vite.config.js"), "export default {};\n");
    mkdirSync(join(created.worktree, "vendor"));
    writeFileSync(join(created.worktree, "vendor", "autoload.php"), "<?php\n");
    writeFileSync(join(created.worktree, ".env"), "APP_KEY=base64:generated\n");
    mkdirSync(join(created.worktree, "public", "build"), { recursive: true });
    writeFileSync(join(created.worktree, "public", "build", "manifest.json"), "{}\n");
    await gitCheckpoint(created.worktree, "Bootstrap the Laravel app");

    await gitIntegrateWorktree(workspace, created.worktree, created.branch, created.baselineSha);

    assert.equal(existsSync(join(workspace, "vendor", "autoload.php")), true);
    assert.equal(existsSync(join(workspace, ".env")), true);
    assert.equal(existsSync(join(workspace, "public", "build", "manifest.json")), true);
  } finally {
    rmSync(worktreeRoot, { recursive: true, force: true });
    rmSync(workspace, { recursive: true, force: true });
  }
});

test("worktree integration refuses a source repository that moved", async () => {
  const { workspace } = initRepository();
  const worktreeRoot = mkdtempSync(join(tmpdir(), "gateway-worktrees-"));
  const runId = "4198f342-7b3d-4a21-8c11-63c7b229d881";
  try {
    const created = await gitCreateWorktree(workspace, runId, worktreeRoot);
    writeFileSync(join(created.worktree, "isolated.txt"), "mission change\n");
    await gitCheckpoint(created.worktree, "Task 1: isolated change");
    writeFileSync(join(workspace, "external.txt"), "external change\n");
    await gitCheckpoint(workspace, "External source change");

    await assert.rejects(
      gitIntegrateWorktree(
        workspace,
        created.worktree,
        created.branch,
        created.baselineSha,
      ),
      /Source repository moved from baseline/,
    );
    assert.equal(existsSync(created.worktree), true);
    assert.equal(existsSync(join(workspace, "isolated.txt")), false);
  } finally {
    rmSync(worktreeRoot, { recursive: true, force: true });
    rmSync(workspace, { recursive: true, force: true });
  }
});

test("parallel task worktrees merge non-conflicting changes into the mission", async () => {
  const { workspace, git } = initRepository();
  const worktreeRoot = mkdtempSync(join(tmpdir(), "gateway-worktrees-"));
  try {
    const first = await gitCreateTaskWorktree(
      workspace,
      "5198f342-7b3d-4a21-8c11-63c7b229d880",
      worktreeRoot,
    );
    const second = await gitCreateTaskWorktree(
      workspace,
      "6198f342-7b3d-4a21-8c11-63c7b229d880",
      worktreeRoot,
    );
    writeFileSync(join(first.worktree, "first.txt"), "first task\n");
    writeFileSync(join(second.worktree, "second.txt"), "second task\n");
    await gitCheckpoint(first.worktree, "First parallel task");
    await gitCheckpoint(second.worktree, "Second parallel task");

    await gitIntegrateTaskWorktree(
      workspace,
      first.worktree,
      first.branch,
      first.baselineSha,
    );
    await gitIntegrateTaskWorktree(
      workspace,
      second.worktree,
      second.branch,
      second.baselineSha,
    );

    assert.equal(existsSync(join(workspace, "first.txt")), true);
    assert.equal(existsSync(join(workspace, "second.txt")), true);
    assert.match(git("log", "--format=%s", "-2").toString(), /Merge branch/);
  } finally {
    rmSync(worktreeRoot, { recursive: true, force: true });
    rmSync(workspace, { recursive: true, force: true });
  }
});

test("conflicting task integration aborts without changing the mission", async () => {
  const { workspace, git } = initRepository();
  const worktreeRoot = mkdtempSync(join(tmpdir(), "gateway-worktrees-"));
  try {
    writeFileSync(join(workspace, "shared.txt"), "baseline\n");
    await gitCheckpoint(workspace, "Add shared file");
    const first = await gitCreateTaskWorktree(
      workspace,
      "7198f342-7b3d-4a21-8c11-63c7b229d880",
      worktreeRoot,
    );
    const second = await gitCreateTaskWorktree(
      workspace,
      "8198f342-7b3d-4a21-8c11-63c7b229d880",
      worktreeRoot,
    );
    writeFileSync(join(first.worktree, "shared.txt"), "first\n");
    writeFileSync(join(second.worktree, "shared.txt"), "second\n");
    await gitCheckpoint(first.worktree, "First conflicting task");
    await gitCheckpoint(second.worktree, "Second conflicting task");
    await gitIntegrateTaskWorktree(
      workspace,
      first.worktree,
      first.branch,
      first.baselineSha,
    );
    const beforeConflict = git("rev-parse", "HEAD").toString().trim();

    let conflict;
    try {
      await gitIntegrateTaskWorktree(
        workspace,
        second.worktree,
        second.branch,
        second.baselineSha,
      );
      assert.fail("Expected task integration to conflict");
    } catch (error) {
      conflict = error;
    }
    assert.match(conflict.message, /conflict with the mission workspace/);
    assert.deepEqual(conflict.conflictFiles, ["shared.txt"]);

    assert.equal(git("rev-parse", "HEAD").toString().trim(), beforeConflict);
    assert.equal(git("status", "--porcelain").toString().trim(), "");
    assert.equal(existsSync(second.worktree), true);
    const report = await gitTaskWorktreeReport(
      workspace,
      second.worktree,
      second.branch,
      second.baselineSha,
    );
    assert.match(report.taskChanges, /shared.txt/);
    assert.match(report.missionChanges, /shared.txt/);
    assert.match(report.diff, /second/);
  } finally {
    rmSync(worktreeRoot, { recursive: true, force: true });
    rmSync(workspace, { recursive: true, force: true });
  }
});

test("gitCreateTaskWorktree copies gitignored dependency directories from the mission workspace", async () => {
  const { workspace, git } = initRepository();
  const worktreeRoot = mkdtempSync(join(tmpdir(), "gateway-worktrees-"));
  try {
    writeFileSync(join(workspace, ".gitignore"), "/vendor\n");
    writeFileSync(join(workspace, "composer.json"), "{}\n");
    mkdirSync(join(workspace, "vendor"));
    writeFileSync(join(workspace, "vendor", "autoload.php"), "<?php\n");
    await gitCheckpoint(workspace, "Scaffold the Laravel app");
    assert.equal(git("status", "--porcelain").toString().trim(), "");

    const created = await gitCreateTaskWorktree(
      workspace,
      "b198f342-7b3d-4a21-8c11-63c7b229d880",
      worktreeRoot,
    );

    assert.equal(existsSync(join(created.worktree, "vendor", "autoload.php")), true);
  } finally {
    rmSync(worktreeRoot, { recursive: true, force: true });
    rmSync(workspace, { recursive: true, force: true });
  }
});

test("gitIntegrateTaskWorktree copies gitignored dependency directories into the mission workspace", async () => {
  const { workspace } = initRepository();
  const worktreeRoot = mkdtempSync(join(tmpdir(), "gateway-worktrees-"));
  try {
    writeFileSync(join(workspace, ".gitignore"), "/vendor\n");
    writeFileSync(join(workspace, "composer.json"), "{}\n");
    await gitCheckpoint(workspace, "Add composer manifest");
    const task = await gitCreateTaskWorktree(
      workspace,
      "c198f342-7b3d-4a21-8c11-63c7b229d880",
      worktreeRoot,
    );
    mkdirSync(join(task.worktree, "vendor"));
    writeFileSync(join(task.worktree, "vendor", "autoload.php"), "<?php\n");
    writeFileSync(join(task.worktree, "app.php"), "scaffolded\n");
    await gitCheckpoint(task.worktree, "Scaffold the app");

    await gitIntegrateTaskWorktree(workspace, task.worktree, task.branch, task.baselineSha);

    assert.equal(existsSync(join(workspace, "vendor", "autoload.php")), true);
    assert.equal(existsSync(join(workspace, "app.php")), true);
  } finally {
    rmSync(worktreeRoot, { recursive: true, force: true });
    rmSync(workspace, { recursive: true, force: true });
  }
});

test("gitCreateTaskWorktree copies a generated .env from the mission workspace", async () => {
  const { workspace, git } = initRepository();
  const worktreeRoot = mkdtempSync(join(tmpdir(), "gateway-worktrees-"));
  try {
    writeFileSync(join(workspace, ".gitignore"), "/.env\n");
    writeFileSync(join(workspace, ".env.example"), "APP_KEY=\n");
    writeFileSync(join(workspace, ".env"), "APP_KEY=base64:generated\n");
    await gitCheckpoint(workspace, "Bootstrap the Laravel app");
    assert.equal(git("status", "--porcelain").toString().trim(), "");

    const created = await gitCreateTaskWorktree(
      workspace,
      "d198f342-7b3d-4a21-8c11-63c7b229d880",
      worktreeRoot,
    );

    assert.equal(existsSync(join(created.worktree, ".env")), true);
  } finally {
    rmSync(worktreeRoot, { recursive: true, force: true });
    rmSync(workspace, { recursive: true, force: true });
  }
});

test("gitIntegrateTaskWorktree copies a task's generated .env into the mission workspace", async () => {
  const { workspace } = initRepository();
  const worktreeRoot = mkdtempSync(join(tmpdir(), "gateway-worktrees-"));
  try {
    writeFileSync(join(workspace, ".gitignore"), "/.env\n");
    await gitCheckpoint(workspace, "Init repository");
    const task = await gitCreateTaskWorktree(
      workspace,
      "e198f342-7b3d-4a21-8c11-63c7b229d880",
      worktreeRoot,
    );
    writeFileSync(join(task.worktree, ".env.example"), "APP_KEY=\n");
    writeFileSync(join(task.worktree, ".env"), "APP_KEY=base64:generated\n");
    await gitCheckpoint(task.worktree, "Bootstrap the Laravel app");

    await gitIntegrateTaskWorktree(workspace, task.worktree, task.branch, task.baselineSha);

    assert.equal(existsSync(join(workspace, ".env")), true);
  } finally {
    rmSync(worktreeRoot, { recursive: true, force: true });
    rmSync(workspace, { recursive: true, force: true });
  }
});

test("task conflict resolution prepares and recovers the merge in the task worktree", async () => {
  const { workspace } = initRepository();
  const worktreeRoot = mkdtempSync(join(tmpdir(), "gateway-worktrees-"));
  try {
    writeFileSync(join(workspace, "shared.txt"), "baseline\n");
    await gitCheckpoint(workspace, "Add shared file");
    const first = await gitCreateTaskWorktree(
      workspace,
      "9198f342-7b3d-4a21-8c11-63c7b229d880",
      worktreeRoot,
    );
    const second = await gitCreateTaskWorktree(
      workspace,
      "a198f342-7b3d-4a21-8c11-63c7b229d880",
      worktreeRoot,
    );
    writeFileSync(join(first.worktree, "shared.txt"), "first\n");
    writeFileSync(join(second.worktree, "shared.txt"), "second\n");
    await gitCheckpoint(first.worktree, "First conflicting task");
    await gitCheckpoint(second.worktree, "Second conflicting task");
    await gitIntegrateTaskWorktree(
      workspace,
      first.worktree,
      first.branch,
      first.baselineSha,
    );

    const prepared = await gitPrepareTaskResolution(
      workspace,
      second.worktree,
      second.branch,
      second.baselineSha,
    );
    assert.equal(prepared.prepared, true);
    assert.equal(prepared.recovered, false);
    assert.deepEqual(prepared.conflictFiles, ["shared.txt"]);
    assert.match(
      readFileSync(join(second.worktree, "shared.txt"), "utf8"),
      /<<<<<<< HEAD/,
    );

    const recovered = await gitPrepareTaskResolution(
      workspace,
      second.worktree,
      second.branch,
      second.baselineSha,
    );
    assert.equal(recovered.recovered, true);
    assert.deepEqual(recovered.conflictFiles, ["shared.txt"]);
  } finally {
    rmSync(worktreeRoot, { recursive: true, force: true });
    rmSync(workspace, { recursive: true, force: true });
  }
});
