from __future__ import annotations

import asyncio
import logging
import uuid
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from starlette.types import ASGIApp, Message, Receive, Scope, Send

from mission_control.api.v1.router import api_router
from mission_control.application.services.agents import AgentService
from mission_control.application.services.job_dispatch import dispatch_loop
from mission_control.application.services.maintenance_scheduler import (
    maintenance_scheduler_loop,
)
from mission_control.core.config import get_settings
from mission_control.core.logging import configure_logging
from mission_control.infrastructure.database.session import async_session_factory, close_database

settings = get_settings()
configure_logging(settings.log_level)
logger = logging.getLogger(__name__)


class RequestIdMiddleware:
    """Attach a request ID outside FastAPI's exception middleware."""

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        request_id = next(
            (
                value.decode("latin-1")
                for name, value in scope["headers"]
                if name.lower() == b"x-request-id"
            ),
            str(uuid.uuid4()),
        )

        async def send_with_request_id(message: Message) -> None:
            if message["type"] == "http.response.start":
                headers = [
                    (name, value)
                    for name, value in message.get("headers", [])
                    if name.lower() != b"x-request-id"
                ]
                headers.append((b"x-request-id", request_id.encode("latin-1")))
                message["headers"] = headers
            await send(message)

        await self.app(scope, receive, send_with_request_id)


async def seed_default_agents() -> None:
    try:
        async with async_session_factory() as session:
            created = await AgentService(session).seed_defaults()
    except Exception:
        logger.warning("default_agent_seeding_skipped", exc_info=True)
        return
    if created:
        logger.info("default_agents_seeded", extra={"count": created})


@asynccontextmanager
async def lifespan(_: FastAPI) -> AsyncIterator[None]:
    logger.info("mission_control_started", extra={"environment": settings.environment})
    await seed_default_agents()
    dispatch_stop = asyncio.Event()
    dispatcher = asyncio.create_task(dispatch_loop(dispatch_stop))
    scheduler = asyncio.create_task(maintenance_scheduler_loop(dispatch_stop))
    yield
    dispatch_stop.set()
    await dispatcher
    await scheduler
    await close_database()
    logger.info("mission_control_stopped")


def create_application() -> FastAPI:
    application = FastAPI(
        title=settings.app_name,
        version="0.1.0",
        lifespan=lifespan,
    )

    application.include_router(api_router, prefix="/api/v1")
    return application


def wrap_application(
    application: FastAPI, cors_origins: list[str] | None = None
) -> ASGIApp:
    """Keep transport headers on responses generated by ServerErrorMiddleware."""

    return CORSMiddleware(
        app=RequestIdMiddleware(application),
        allow_origins=cors_origins or settings.api_cors_origins,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )


application = create_application()
app = wrap_application(application)
